<a href="https://colab.research.google.com/github/Sam-Joshua-S/100DaysOfData/blob/main/Day%2016%20pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
t1 = torch.tensor(5)

In [5]:
t1

tensor(5)

In [6]:
t1.dtype

torch.int64

In [7]:
t4 = torch.tensor([[1,2],[4,5]])

In [8]:
t1.shape

torch.Size([])

In [9]:
t4.shape

torch.Size([2, 2])

In [10]:
t2 = torch.tensor([[1]])

In [11]:
t2.shape

torch.Size([1, 1])

#Tensor Operation and Gradient 

In [17]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(7.,requires_grad=True)

In [18]:
y = w * x + b
y

tensor(19., grad_fn=<AddBackward0>)

In [19]:
y.backward()

In [20]:
print("dy/dx",x.grad)
print("dy/dw",w.grad)
print("dy/db",b.grad)


dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


#Interoperability with numpy

In [21]:
import numpy as np
x = np.array([[1,2],[4,5]])

In [22]:
x

array([[1, 2],
       [4, 5]])

In [23]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [4, 5]])

In [24]:
x.dtype , y.dtype

(dtype('int64'), torch.int64)

In [25]:
z = y.numpy()
z

array([[1, 2],
       [4, 5]])

#Linear Regression

In [26]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

In [27]:
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [28]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)


In [29]:
w = torch.randn(2,3,requires_grad=True)
b = torch.randn(2,requires_grad=True)

In [32]:
print(inputs.shape,w.shape,b.shape,targets.shape)

torch.Size([5, 3]) torch.Size([2, 3]) torch.Size([2]) torch.Size([5, 2])


<img src="https://i.imgur.com/WGXLFvA.png">

## @ represent matrix multiplication

In [33]:
def model(x):
  return x @ w.t() + b

In [43]:
# Before Optimization
preds = model(inputs)

In [44]:
preds

tensor([[  28.8771, -111.8078],
        [  38.7261, -158.4703],
        [ -19.7641, -189.3305],
        [  78.0536,  -76.8099],
        [  13.6449, -178.5150]], grad_fn=<AddBackward0>)

In [45]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


## numel represent no of element

In [48]:
def mse(t1,t2):
  diff = t1-t2
  return torch.sum(diff*diff) / diff.numel()

In [49]:
loss = mse(preds,targets)

In [50]:
print(loss)

tensor(33864.8242, grad_fn=<DivBackward0>)


##Compute Gradient Descent

In [51]:
loss.backward()

In [53]:
print(w)
print(w.grad)

tensor([[ 0.9473, -1.0915,  0.7486],
        [ 0.1844, -0.8539, -1.5262]], requires_grad=True)
tensor([[ -3669.4832,  -6059.9038,  -3220.2024],
        [-19412.7305, -22332.4102, -13631.2031]])


#We use torch.no_grad to indicate to PyTorch that we shouldn't track, calculate, or modify gradients while updating the weights and biases.

In [57]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [ ]:
loss = mse(preds, targets)
print(loss)

In [59]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [60]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[ 53.2482,  -6.8192],
        [ 70.9252, -20.3417],
        [ 19.7777, -25.1663],
        [100.6744,  26.5348],
        [ 45.4561, -45.3854]], grad_fn=<AddBackward0>)


In [61]:
# Calculate the loss
loss = mse(preds, targets)
print(loss)

tensor(9222.8770, grad_fn=<DivBackward0>)


In [62]:
# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -1139.1536,  -3301.5903,  -1527.0251],
        [ -8564.0820, -10650.0488,  -6427.3862]])
tensor([ -18.1837, -106.2356])


In [63]:
# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [64]:
print(w)
print(b)

tensor([[ 1.0688, -0.8767,  0.8604],
        [ 0.8524, -0.0774, -1.0530]], requires_grad=True)
tensor([ 0.6695, -2.4278], requires_grad=True)


In [65]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(7011.3047, grad_fn=<DivBackward0>)


In [68]:
for i in range(100):
  preds = model(inputs)
  loss = mse(targets,preds)
  loss.backward()
  with torch.no_grad():
      w -= w.grad * 1e-5
      b -= b.grad * 1e-5
      w.grad.zero_()
      b.grad.zero_()


In [69]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(785.3158, grad_fn=<DivBackward0>)


#Linear Regression using Pytorch Build in 

In [71]:
import torch.nn as nn

In [72]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

# Dataset and DataLoader

In [73]:
from torch.utils.data import TensorDataset

In [76]:
train_ds = TensorDataset(inputs,targets)
train_ds[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]), tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [77]:
model = nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.3025, -0.2175, -0.1778],
        [-0.3736,  0.2846,  0.3502]], requires_grad=True)
Parameter containing:
tensor([ 0.4984, -0.1856], requires_grad=True)


In [78]:
list(model.parameters())

[Parameter containing:
 tensor([[ 0.3025, -0.2175, -0.1778],
         [-0.3736,  0.2846,  0.3502]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4984, -0.1856], requires_grad=True)]

In [79]:
preds = model(inputs)

In [80]:
preds

tensor([[  0.3656,   6.6662],
        [ -2.4899,  13.2717],
        [-12.6387,  25.7554],
        [ 15.4259, -13.0999],
        [-11.9523,  25.8692],
        [  0.8856,   6.0080],
        [ -2.4501,  13.3373],
        [-12.5140,  25.7320],
        [ 14.9058, -12.4417],
        [-12.4326,  26.5930],
        [  0.4053,   6.7318],
        [ -1.9698,  12.6135],
        [-12.6785,  25.6898],
        [ 15.9062, -13.8238],
        [-12.4723,  26.5274]], grad_fn=<AddmmBackward0>)

##Loss Function

In [82]:
import torch.nn.functional as F

In [83]:
loss_fn = F.mse_loss

In [84]:
loss = loss_fn(model(inputs),targets)
loss

tensor(7491.9668, grad_fn=<MseLossBackward0>)

##Optimizer

In [85]:
opt = torch.optim.SGD(model.parameters(),lr = 1e-5)

#Train the model


In [86]:
def fit(num_epoch,model,loss_fn,opt,train_dl):
  for epoch in range(num_epoch):
    for xb,yb in train_dl:
      pred = model(xb)
      loss = loss_fn(pred,yb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if (epoch+1) % 10 == 0:
      print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1,num_epoch,loss.item()))

In [89]:
fit(100,model,loss_fn,opt,train_ds)

Epoch [10/100], Loss: 146.5841
Epoch [20/100], Loss: 47.9156
Epoch [30/100], Loss: 21.6367
Epoch [40/100], Loss: 11.9792
Epoch [50/100], Loss: 7.3272
Epoch [60/100], Loss: 4.6594
Epoch [70/100], Loss: 2.9913
Epoch [80/100], Loss: 1.9156
Epoch [90/100], Loss: 1.2224
Epoch [100/100], Loss: 0.7848


In [90]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[53.4188, 67.7031]], grad_fn=<AddmmBackward0>)